"""Phase 45 actual LLM one-shot call closeout.

This module is report-only. It records the already-observed Manual Gate 3
LLM/OpenRouter one-shot call as a sanitized closeout fixture and never calls an
LLM provider, starts Discord, sends messages, creates embeddings, or executes
external actions.
"""

from __future__ import annotations

import copy
import json
import re
from typing import Any


VERSION = "phase45_actual_llm_one_shot_call_closeout_no_discord_send_lock"
CITATION = "knowledge/operation/stoxl_operation_tone_sample.md"
LONG_ID_RE = re.compile(r"\b\d{15,25}\b")
SECRET_RE = re.compile(r"(?i)(sk-[a-z0-9_-]+|xoxb-[a-z0-9_-]+|mfa\.|bearer\s+\S+|api[_ -]?key\s*[:=]\s*\S+|token\s*[:=]\s*\S+|password\s*[:=]\s*\S+)")
APPROVAL_PHRASE_RE = re.compile(r"I_APPROVE_[A-Z0-9_]+")


def build_success_fixture() -> dict[str, Any]:
    return {
        "report_type": "phase45_actual_llm_call_closeout",
        "version": VERSION,
        "closeout_available": True,
        "report_only": True,
        "source_manual_gate3_actual_llm_call_observed": True,
        "phase45_actual_llm_one_shot_completed": True,
        "phase45_actual_llm_call_count": 1,
        "phase45_ready_for_repeat_llm_call": False,
        "phase45_actual_llm_one_shot_repeat_locked": True,
        "phase45_actual_llm_one_shot_already_consumed": True,
        "agent": "kasumi",
        "allowed_sources": ["operation"],
        "evidence_citations": [CITATION],
        "provider": "openrouter",
        "provider_value_logged": True,
        "model_present": True,
        "model_value_logged": False,
        "provider_usage_present": True,
        "usage": {
            "prompt_tokens": 143,
            "completion_tokens": 209,
            "total_tokens": 352,
            "cost_present": True,
            "cost_value_logged": False,
        },
        "llm_api_call_attempted": True,
        "llm_api_called": True,
        "llm_api_call_count": 1,
        "llm_api_call_attempted_count": 1,
        "llm_api_called_count": 1,
        "actual_llm_api_call_attempted": True,
        "actual_llm_api_called": True,
        "real_llm_api_call_count": 1,
        "additional_llm_api_call": False,
        "llm_response_packet_created": False,
        "llm_response_review_only": False,
        "output_safety_checked": True,
        "output_safety_allowed": False,
        "output_safety_blocked": True,
        "output_safety": {
            "blocked": True,
            "blocked_reasons": ["external_action_claim"],
            "safe_disclaimer_detected": True,
            "safe_disclaimer_reasons": ["negated_external_action", "review_only"],
            "false_positive_review_recommended": True,
        },
        "output_safety_false_positive_possible": True,
        "output_safety_requires_phase46_review": True,
        "discord_live_runtime_executed_by_closeout": False,
        "discord_api_send_called": False,
        "discord_message_sent": False,
        "message_sent_count": 0,
        "ready_for_discord_send": False,
        "ready_for_discord_send_phase": False,
        "ready_for_unattended_auto_reply": False,
        "public_channel_send_called": False,
        "team_channel_send_called": False,
        "public_channel_reply_allowed": False,
        "team_channel_reply_allowed": False,
        "unattended_auto_reply_allowed": False,
        "embedding_api_called": False,
        "vector_index_created": False,
        "external_execution": False,
        "approval_phrase_generated": False,
        "manual_approval_actualized_for_send": False,
        "full_content_included": False,
        "response_preview_only": True,
        "response_preview": (
            "Review-only Kasumi operation draft was generated by the observed Manual Gate 3 LLM call. "
            "Output safety blocked it, and no Discord send or external action was performed."
        ),
        "phase36d_actual_llm_draft_call_complete": True,
        "phase36e_closeout_passed": True,
        "phase45_closeout_passed": True,
        "ready_for_phase36f_no_send_final_lock": True,
        "safety_assertions": {
            "api_key_value_logged": False,
            "token_value_logged": False,
            "raw_discord_ids_logged": False,
            "approval_phrase_value_logged": False,
            "full_content_included": False,
            "embedding_called": False,
            "vector_index_created": False,
            "external_execution": False,
            "discord_message_sent": False,
            "public_channel_send_called": False,
            "team_channel_send_called": False,
            "llm_call_count": 1,
        },
    }


def build_actual_one_shot_llm_draft_call_closeout(report: dict[str, Any] | None = None) -> dict[str, Any]:
    closeout = copy.deepcopy(report) if report is not None else build_success_fixture()
    closeout.setdefault("report_type", "phase45_actual_llm_call_closeout")
    closeout.setdefault("version", VERSION)
    closeout["closeout_available"] = True
    closeout["report_only"] = True
    closeout["phase45_actual_llm_one_shot_completed"] = bool(closeout.get("phase45_actual_llm_one_shot_completed", True))
    closeout["phase45_actual_llm_call_count"] = int(closeout.get("phase45_actual_llm_call_count", closeout.get("llm_api_call_count", 1)) or 0)
    closeout.setdefault("llm_api_call_attempted_count", int(closeout.get("llm_api_call_count", 0) or 0))
    closeout.setdefault("llm_api_called_count", int(closeout.get("llm_api_call_count", 0) or 0))
    closeout.setdefault("phase45_ready_for_repeat_llm_call", False)
    closeout.setdefault("phase45_actual_llm_one_shot_repeat_locked", True)
    closeout.setdefault("phase45_actual_llm_one_shot_already_consumed", True)
    closeout["additional_llm_api_call"] = False
    closeout["discord_live_runtime_executed_by_closeout"] = False
    closeout.setdefault("discord_api_send_called", False)
    closeout.setdefault("discord_message_sent", False)
    closeout["message_sent_count"] = int(closeout.get("message_sent_count", 0) or 0)
    closeout.setdefault("ready_for_discord_send", False)
    closeout.setdefault("ready_for_discord_send_phase", False)
    closeout.setdefault("ready_for_unattended_auto_reply", False)
    closeout.setdefault("public_channel_send_called", False)
    closeout.setdefault("team_channel_send_called", False)
    closeout.setdefault("public_channel_reply_allowed", False)
    closeout.setdefault("team_channel_reply_allowed", False)
    closeout.setdefault("unattended_auto_reply_allowed", False)
    closeout.setdefault("embedding_api_called", False)
    closeout.setdefault("vector_index_created", False)
    closeout.setdefault("external_execution", False)
    closeout.setdefault("approval_phrase_generated", False)
    closeout.setdefault("manual_approval_actualized_for_send", False)
    closeout.setdefault("full_content_included", False)
    closeout.setdefault("response_preview_only", True)
    closeout.setdefault("model_present", True)
    closeout["model_value_logged"] = False
    closeout.setdefault("provider_usage_present", True)
    closeout.setdefault("safety_assertions", {})
    safety = closeout["safety_assertions"]
    safety.setdefault("api_key_value_logged", False)
    safety.setdefault("token_value_logged", False)
    safety.setdefault("raw_discord_ids_logged", False)
    safety.setdefault("approval_phrase_value_logged", False)
    safety.setdefault("full_content_included", False)
    safety.setdefault("embedding_called", False)
    safety.setdefault("vector_index_created", False)
    safety.setdefault("external_execution", False)
    safety.setdefault("discord_message_sent", False)
    safety.setdefault("public_channel_send_called", False)
    safety.setdefault("team_channel_send_called", False)
    safety["llm_call_count"] = int(closeout.get("llm_api_call_count", 0) or 0)
    closeout["phase45_closeout_passed"] = _passes_closeout(closeout)
    closeout["phase36e_closeout_passed"] = bool(closeout["phase45_closeout_passed"])
    closeout["phase36d_actual_llm_draft_call_complete"] = bool(closeout["phase45_closeout_passed"])
    closeout["ready_for_phase36f_no_send_final_lock"] = bool(closeout["phase45_closeout_passed"])
    assert_actual_one_shot_llm_draft_call_closeout_safe(closeout)
    return closeout


def _passes_closeout(report: dict[str, Any]) -> bool:
    safety = report.get("output_safety", {}) if isinstance(report.get("output_safety"), dict) else {}
    return bool(
        report.get("source_manual_gate3_actual_llm_call_observed")
        and report.get("phase45_actual_llm_one_shot_completed")
        and int(report.get("phase45_actual_llm_call_count", 0) or 0) == 1
        and not report.get("phase45_ready_for_repeat_llm_call")
        and report.get("phase45_actual_llm_one_shot_repeat_locked")
        and report.get("agent") == "kasumi"
        and report.get("allowed_sources") == ["operation"]
        and report.get("evidence_citations") == [CITATION]
        and report.get("provider") == "openrouter"
        and report.get("model_present")
        and report.get("provider_usage_present")
        and int(report.get("llm_api_call_count", 0) or 0) == 1
        and report.get("llm_api_call_attempted")
        and report.get("llm_api_called")
        and report.get("actual_llm_api_call_attempted")
        and report.get("actual_llm_api_called")
        and int(report.get("real_llm_api_call_count", 0) or 0) == 1
        and not report.get("llm_response_packet_created")
        and report.get("output_safety_checked")
        and not report.get("output_safety_allowed")
        and report.get("output_safety_blocked")
        and "external_action_claim" in list(safety.get("blocked_reasons", []))
        and safety.get("safe_disclaimer_detected")
        and not report.get("discord_api_send_called")
        and not report.get("discord_message_sent")
        and int(report.get("message_sent_count", 0) or 0) == 0
        and not report.get("ready_for_discord_send")
        and not report.get("embedding_api_called")
        and not report.get("vector_index_created")
        and not report.get("external_execution")
        and not report.get("full_content_included")
        and report.get("response_preview_only")
    )


def assert_actual_one_shot_llm_draft_call_closeout_safe(report: dict[str, Any]) -> None:
    text = json.dumps(report, ensure_ascii=False)
    lowered = text.lower()
    if SECRET_RE.search(lowered):
        raise ValueError("Phase 45 closeout contains secret-like values.")
    if LONG_ID_RE.search(text):
        raise ValueError("Phase 45 closeout contains raw Discord-like IDs.")
    if APPROVAL_PHRASE_RE.search(text):
        raise ValueError("Phase 45 closeout contains approval phrase values.")
    if int(report.get("llm_api_call_count", 0) or 0) != 1:
        raise ValueError("Phase 45 closeout LLM call count must be exactly 1.")
    if int(report.get("phase45_actual_llm_call_count", 0) or 0) != 1:
        raise ValueError("Phase 45 closeout actual LLM call count must be exactly 1.")
    if not report.get("actual_llm_api_call_attempted") or not report.get("actual_llm_api_called"):
        raise ValueError("Phase 45 closeout must record the observed actual LLM call.")
    if int(report.get("real_llm_api_call_count", 0) or 0) != 1:
        raise ValueError("Phase 45 closeout real LLM call count must be exactly 1.")
    if report.get("llm_response_packet_created"):
        raise ValueError("Phase 45 closeout must not create a response packet for blocked output.")
    if not report.get("output_safety_checked") or report.get("output_safety_allowed") or not report.get("output_safety_blocked"):
        raise ValueError("Phase 45 closeout output safety must be blocked.")
    for key in (
        "additional_llm_api_call",
        "phase45_ready_for_repeat_llm_call",
        "discord_live_runtime_executed_by_closeout",
        "discord_api_send_called",
        "discord_message_sent",
        "ready_for_discord_send",
        "ready_for_discord_send_phase",
        "public_channel_send_called",
        "team_channel_send_called",
        "public_channel_reply_allowed",
        "team_channel_reply_allowed",
        "unattended_auto_reply_allowed",
        "embedding_api_called",
        "vector_index_created",
        "external_execution",
        "approval_phrase_generated",
        "manual_approval_actualized_for_send",
        "full_content_included",
        "ready_for_unattended_auto_reply",
    ):
        if report.get(key):
            raise ValueError(f"Phase 45 closeout unsafe flag is true: {key}")
    if int(report.get("message_sent_count", 0) or 0) != 0:
        raise ValueError("Phase 45 closeout message sent count must be 0.")
    if not report.get("response_preview_only"):
        raise ValueError("Phase 45 closeout must be preview-only.")
    safety = report.get("safety_assertions", {})
    for key in (
        "api_key_value_logged",
        "token_value_logged",
        "raw_discord_ids_logged",
        "approval_phrase_value_logged",
        "full_content_included",
        "embedding_called",
        "vector_index_created",
        "external_execution",
        "discord_message_sent",
        "public_channel_send_called",
        "team_channel_send_called",
    ):
        if safety.get(key):
            raise ValueError(f"Phase 45 closeout unsafe assertion is true: {key}")
    if int(safety.get("llm_call_count", 0) or 0) != 1:
        raise ValueError("Phase 45 closeout safety assertion LLM call count must be 1.")
    if not report.get("phase45_closeout_passed"):
        raise ValueError("Phase 45 closeout required conditions did not pass.")


def render_actual_one_shot_llm_draft_call_closeout_markdown(report: dict[str, Any]) -> str:
    usage = report.get("usage", {}) if isinstance(report.get("usage"), dict) else {}
    return "\n".join(
        [
            "# STOXL Phase45 Actual LLM One-shot Call Closeout",
            "",
            f"- Phase45 closeout passed: {str(report.get('phase45_closeout_passed')).lower()}",
            f"- Report only: {str(report.get('report_only')).lower()}",
            f"- Manual Gate 3 observed: {str(report.get('source_manual_gate3_actual_llm_call_observed')).lower()}",
            f"- Phase45 actual LLM one-shot completed: {str(report.get('phase45_actual_llm_one_shot_completed')).lower()}",
            f"- Phase45 actual LLM call count: {report.get('phase45_actual_llm_call_count', 0)}",
            f"- Phase45 ready for repeat LLM call: {str(report.get('phase45_ready_for_repeat_llm_call')).lower()}",
            f"- Agent: {report.get('agent', '')}",
            f"- Sources: {', '.join(report.get('allowed_sources', []))}",
            f"- Provider: {report.get('provider', '')}",
            f"- Model present: {str(report.get('model_present')).lower()}",
            f"- Provider usage present: {str(report.get('provider_usage_present')).lower()}",
            f"- Total tokens: {usage.get('total_tokens', 0)}",
            f"- LLM API call attempted: {str(report.get('llm_api_call_attempted')).lower()}",
            f"- LLM API called: {str(report.get('llm_api_called')).lower()}",
            f"- Actual LLM API called: {str(report.get('actual_llm_api_called')).lower()}",
            f"- Real LLM API call count: {report.get('real_llm_api_call_count', 0)}",
            f"- Output safety blocked: {str(report.get('output_safety_blocked')).lower()}",
            f"- LLM response packet created: {str(report.get('llm_response_packet_created')).lower()}",
            "- Discord API send called: false",
            "- Discord message sent: false",
            "- Message sent count: 0",
            "- Ready for Discord send: false",
            "- Additional LLM API call by closeout: false",
            "- Embedding API called: false",
            "- External execution: false",
        ]
    ) + "\n"
