"""Phase 30 routing report and would-send preview tests.

Run without pytest:
  python apps\hermes_gateway\tests\test_would_send_preview.py
"""

from __future__ import annotations

import sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1]
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from live_event_audit_persistence import build_live_event_audit_record, build_sample_visibility_event
from live_event_routing_report import build_live_event_routing_report, resolve_agent_route_candidate
from would_send_preview import build_would_send_preview


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def audit_record(workflow_role: str = "marketing_intake") -> dict:
    event = build_sample_visibility_event()
    event["workflow_role"] = workflow_role
    return build_live_event_audit_record(event, content="hello")


def test_routing_report_created() -> None:
    report = build_live_event_routing_report(audit_record())
    assert_true(report["report_type"] == "live_event_routing_report", "Routing report should be created")


def test_marketing_intake_to_marin() -> None:
    assert_true(resolve_agent_route_candidate("marketing_intake") == "marin", "marketing_intake should route to marin")


def test_senior_review_to_lucy() -> None:
    assert_true(resolve_agent_route_candidate("senior_review") == "lucy", "senior_review should route to lucy")


def test_senior_operation_review_to_meiko() -> None:
    assert_true(resolve_agent_route_candidate("senior_operation_review") == "meiko", "senior_operation_review should route to meiko")


def test_strategy_planning_to_reze() -> None:
    assert_true(resolve_agent_route_candidate("strategy_planning") == "reze", "strategy_planning should route to reze")


def test_unknown_to_unrouted() -> None:
    assert_true(resolve_agent_route_candidate("unknown") == "unrouted", "unknown workflow should be unrouted")


def test_would_send_preview_created() -> None:
    record = audit_record()
    routing = build_live_event_routing_report(record)
    preview = build_would_send_preview(record, routing)
    assert_true(preview["preview_type"] == "would_send_preview", "Preview should be created")


def test_would_send_flags_false() -> None:
    record = audit_record()
    preview = build_would_send_preview(record, build_live_event_routing_report(record))
    assert_true(preview["will_send"] is False, "will_send should be false")
    assert_true(preview["message_sent"] is False, "message_sent should be false")
    assert_true(preview["llm_called"] is False, "llm_called should be false")
    assert_true(preview["rag_called"] is False, "rag_called should be false")
    assert_true(preview["external_execution"] is False, "external_execution should be false")


def test_deterministic_placeholder_only() -> None:
    record = audit_record()
    preview = build_would_send_preview(record, build_live_event_routing_report(record))
    assert_true(preview["content_preview"].startswith("[NO SEND]"), "Preview should be deterministic placeholder")
    assert_true("Reply generation is disabled." in preview["content_preview"], "Preview should not be generated by LLM")


def main() -> int:
    tests = [
        test_routing_report_created,
        test_marketing_intake_to_marin,
        test_senior_review_to_lucy,
        test_senior_operation_review_to_meiko,
        test_strategy_planning_to_reze,
        test_unknown_to_unrouted,
        test_would_send_preview_created,
        test_would_send_flags_false,
        test_deterministic_placeholder_only,
    ]
    for test in tests:
        test()
        print(f"PASS {test.__name__}")
    print("All would-send preview tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
